### ISSUE TITLE
Build error with material 5.0.0-rc0

### ISSUE THREAD

**Issue by Hainesy** [albertnadal/ng2-daterange-picker#10]
ERROR in node_modules/ng2-daterange-picker/node_modules/@angular/material/chips/typings/chip-list.d.ts(27,22): error TS2420: Class 'MatChipList' incorrectly implements interface 'MatFormFieldControl<any>'.
  Types of property 'stateChanges' are incompatible.
    Type 'Subject<void>' is not assignable to type 'Observable<void>'.
      Types of property 'lift' are incompatible.
        Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<void, R>) => Observable<R>'.
          Type 'Observable<void>' is not assignable to type 'Observable<R>'.
            Type 'void' is not assignable to type 'R'.
node_modules/ng2-daterange-picker/node_modules/@angular/material/input/typings/input.d.ts(15,22): error TS2420: Class 'MatInput' incorrectly implements interface 'MatFormFieldControl<any>'.
  Types of property 'stateChanges' are incompatible.
    Type 'Subject<void>' is not assignable to type 'Observable<void>'.
node_modules/ng2-daterange-picker/node_modules/@angular/material/select/typings/select.d.ts(73,22): error TS2420: Class 'MatSelect' incorrectly implements interface 'MatFormFieldControl<any>'.
  Types of property 'stateChanges' are incompatible.
    Type 'Subject<void>' is not assignable to type 'Observable<void>'.
node_modules/ng2-daterange-picker/node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
node_modules/ng2-daterange-picker/src/daterange.picker.module.ts(4,10): error TS2305: Module '"C:/Users/chris/repos/serenity/tc-ng-product/node_modules/ng2-daterange-picker/node_modules/@angular/material/material"' has no exported member 'MaterialModule'.

**Comment by dustinblanchard** [comment]
I've addressed this in my fork, PR #11

**Comment by dustinblanchard** [comment]
@albertnadal could you update the version in NPM to reflect this merge?

**Comment by iamwhitebox** [comment]
@albertnadal @dustinblanchard  was this ever addressed? pulling from master I still get these error(s)

**Comment by dustinblanchard** [comment]
@iamwhitebox it's fixed on my fork, but @albertnadal still hasn't updated it in NPM as far as I know.

**Comment by RoopeHakulinen** [comment]
@albertnadal Thank you for this great library. Would be awesome to get the changes of that PR released so that usage with newest @angular/material would be possible :)

**Comment by JStein92** [comment]
@albertnadal Can you please update in NPM?

**Comment by iamwhitebox** [comment]
I see the package has been updated, but now I get this error

`ERROR in ./node_modules/ng2-daterange-picker/index.ts
Module build failed: Error: /Users/jonej371/IdeaProjects/dmc-content-services/cmt-frontend/src/main/frontend/node_modules/ng2-daterange-picker/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.`

`The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).`

Could this be due to an issue with the angular package format? Is anyone else experiencing this issue?

**Comment by iamwhitebox** [comment]
`npm link ng2-daterange-picker` seemed to solved the above error, but

Still more build errors... 

```
ERROR in node_modules/ng2-daterange-picker/node_modules/@angular/material/table/typings/table-data-source.d.ts(21,22): error TS2420: Class 'MatTableDataSource<T>' incorrectly implements interface 'DataSource<T>'.
  Types of property 'connect' are incompatible.
    Type '() => BehaviorSubject<T[]>' is not assignable to type '(collectionViewer: CollectionViewer) => Observable<T[]>'.
      Type 'BehaviorSubject<T[]>' is not assignable to type 'Observable<T[]>'.
        Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
```

**Comment by iamwhitebox** [comment]
@dustinblanchard are you experiencing these issue(s) ?

**Comment by ghost** [comment]
I have the same issue than imwhitebox. I'm working on angular 5.2.3 / typescript 2.6.2.

**Comment by GadyTal** [comment]
I have the same issue as @imwhitebox.
